# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Emre Hayırcı
tagline:          'Emre Hayırcı'
description:      'Software Developer,Student at Dokuz Eylul University Computer Engineering. Much more interested in ML, Python, Django, Js, React, ReactNative, Native Android Development. '
url:              http://emrehayirci.github.io
baseurl:          /

author:
  name:           'Emre Hayırcı'
  url:            https://twitter.com/emrehayirci

paginate:         5

# Custom vars
version:          2.1.0

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

github:
  repo:           https://github.com/poole/hyde
